name: Frontend CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd frontend
          yarn install --frozen-lockfile

      - name: Lint code
        run: |
          cd frontend
          yarn lint

      - name: Run tests
        run: |
          cd frontend
          yarn test:ci

      - name: Build for production
        run: |
          cd frontend
          yarn build
