name: Frontend CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies (root workspace)
        run: yarn install --frozen-lockfile

      - name: Lint frontend
        run: yarn workspace frontend lint

      - name: Run frontend tests
        run: yarn workspace frontend test:ci

      - name: Build frontend
        run: yarn workspace frontend build
